### ISSUE TITLE
Problema con calendario grid

### ISSUE THREAD

**Issue by francemazzi** [dianaberna/corso-frontend-09-22#35]
Il calendario è venuto con grid ma da un problema... in pratica dovrebbe crearsi un cerchio ma si visualizza un ellisse... @dianaberna 

https://github.com/dianaberna/corso-frontend-09-22/blob/4817a2155361258ca671c021ead5d62f525e1ba9/11_esercizio/style11.css#L230-L275

**Comment by dianaberna** [comment]
prova ad aggiungere queste proprietà 
.giorniSetNumeri > span {
    width: 10px; --> in pratica impostando una dimensione fissi risolvi tutto
    padding-top: 2px; --> ho aggiornato i due padding perché mi sembrava venisse un cerchio un pò storto 
    padding-bottom: 2px;
    text-align: center; --> senza questo il testo rimane sulla sinistra
}

#numeroGiorno:hover {
    cursor: pointer; --> visto che all'hover sono cliccabili anche se non abbiamo qualcosa di reale scritto in js intanto possiamo mettere il cursore giusto 
}

fammi sapere se abbiamo risolto ;)
